// Shared artworks dataset used by portfolio pages
export const artworks = [
	{
		id: 1,
		title: "Urban Jungle",
		type: "mural",
		category: "commercial",
		description:
			"A vibrant mural depicting the harmony between urban life and nature. This piece transforms a concrete wall into a living ecosystem.",
		image: "/canvas/photo_2025-10-11_18-26-00.jpg",
		client: "City Park Cafe",
		year: 2023,
		size: "4m x 3m",
		duration: "2 weeks",
		materials: ["Acrylic paint", "Weather-resistant coating"],
		tags: ["nature", "urban", "colorful", "large-scale"],
		featured: true,
		likes: 127,
		views: 1543,
	},
	{
		id: 2,
		title: "Serenity",
		type: "canvas",
		category: "abstract",
		description:
			"An abstract canvas painting exploring themes of peace and tranquility through flowing forms and calming colors.",
		image: "/canvas/photo_2025-10-11_18-26-02.jpg",
		client: "Private Collection",
		year: 2022,
		size: "80cm x 60cm",
		duration: "1 week",
		materials: ["Oil paint", "Canvas"],
		tags: ["abstract", "peaceful", "blue", "meditation"],
		featured: false,
		likes: 89,
		views: 892,
	},
	{
		id: 3,
		title: "Ocean Dreams",
		type: "canvas",
		category: "nature",
		description:
			"A canvas painting capturing the mesmerizing beauty of ocean waves with dynamic brushstrokes and vivid blues.",
		image: "/canvas/photo_2025-10-11_18-26-31.jpg",
		client: "Coastal Resort",
		year: 2023,
		size: "120cm x 90cm",
		duration: "10 days",
		materials: ["Acrylic paint", "Canvas", "Texture medium"],
		tags: ["ocean", "waves", "blue", "movement"],
		featured: true,
		likes: 156,
		views: 2103,
	},
	{
		id: 4,
		title: "Community Spirit",
		type: "mural",
		category: "public",
		description:
			"A community mural celebrating local heritage and diversity, created with input from neighborhood residents.",
		image: "/murals/photo_2025-10-11_17-53-19.jpg",
		client: "Community Center",
		year: 2021,
		size: "6m x 4m",
		duration: "3 weeks",
		materials: ["Acrylic paint", "Anti-graffiti coating"],
		tags: ["community", "heritage", "colorful", "collaborative"],
		featured: false,
		likes: 203,
		views: 3421,
	},
	{
		id: 5,
		title: "Sunset Reflections",
		type: "canvas",
		category: "nature",
		description: "A canvas painting depicting a breathtaking sunset over still waters with warm, golden tones.",
		image: "/canvas/photo_2025-10-11_18-26-04.jpg",
		client: "Private Residence",
		year: 2022,
		size: "100cm x 70cm",
		duration: "1 week",
		materials: ["Oil paint", "Canvas"],
		tags: ["sunset", "reflection", "warm", "peaceful"],
		featured: false,
		likes: 94,
		views: 1287,
	},
	{
		id: 6,
		title: "Corporate Vision",
		type: "mural",
		category: "commercial",
		description:
			"A corporate mural representing the company's values and vision for the future through modern geometric forms.",
		image: "/murals/photo_2025-10-11_17-53-22.jpg",
		client: "Tech Innovations Inc.",
		year: 2023,
		size: "5m x 2.5m",
		duration: "2 weeks",
		materials: ["Acrylic paint", "Primer"],
		tags: ["corporate", "modern", "geometric", "professional"],
		featured: true,
		likes: 78,
		views: 1156,
	},
	// extra canvas items
	{
		id: 7,
		title: "Canvas Extra 1",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-00.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 8,
		title: "Canvas Extra 2",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-02.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 9,
		title: "Canvas Extra 3",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-03.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 10,
		title: "Canvas Extra 4",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-04.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 11,
		title: "Canvas Extra 5",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-05.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 12,
		title: "Canvas Extra 6",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-07.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 13,
		title: "Canvas Extra 7",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-08.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 14,
		title: "Canvas Extra 8",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-09.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 15,
		title: "Canvas Extra 9",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-10.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 16,
		title: "Canvas Extra 10",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-11.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 17,
		title: "Canvas Extra 11",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-12.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 18,
		title: "Canvas Extra 12",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-14.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 19,
		title: "Canvas Extra 13",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-15.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 20,
		title: "Canvas Extra 14",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-16.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 21,
		title: "Canvas Extra 15",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-17.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 22,
		title: "Canvas Extra 16",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-18.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 23,
		title: "Canvas Extra 17",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-19.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 24,
		title: "Canvas Extra 18",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-20.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 25,
		title: "Canvas Extra 19",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-22.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 26,
		title: "Canvas Extra 20",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-23.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 27,
		title: "Canvas Extra 21",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-24.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 28,
		title: "Canvas Extra 22",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-25.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 29,
		title: "Canvas Extra 23",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-26.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 30,
		title: "Canvas Extra 24",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-27.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 31,
		title: "Canvas Extra 25",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-28.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 32,
		title: "Canvas Extra 26",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-30.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 33,
		title: "Canvas Extra 27",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-31.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 34,
		title: "Canvas Extra 28",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-32.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 35,
		title: "Canvas Extra 29",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-33.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 36,
		title: "Canvas Extra 30",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-34.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 37,
		title: "Canvas Extra 31",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-35.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 38,
		title: "Canvas Extra 32",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-37.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 39,
		title: "Canvas Extra 33",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-38.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 40,
		title: "Canvas Extra 34",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-39.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 41,
		title: "Canvas Extra 35",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-40.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 42,
		title: "Canvas Extra 36",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-42.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 43,
		title: "Canvas Extra 37",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-43.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 44,
		title: "Canvas Extra 38",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-45.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 45,
		title: "Canvas Extra 39",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-46.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
	{
		id: 46,
		title: "Canvas Extra 40",
		type: "canvas",
		category: "abstract",
		description: "Placeholder canvas artwork.",
		image: "/canvas/photo_2025-10-11_18-26-47.jpg",
		client: "Gallery",
		year: 2023,
		size: "60cm x 40cm",
		duration: "3 days",
		materials: ["Acrylic", "Canvas"],
		tags: ["placeholder", "canvas"],
		featured: false,
		likes: 10,
		views: 100,
	},
]

export type Artwork = typeof artworks[number]
